from __future__ import annotations

import os

from langchain_core.documents import Document
from openai import OpenAI
from pydantic import BaseModel, Field


DEFAULT_MODEL = os.getenv(
    "OPENAI_MODEL",
    "gpt-5.6",
)


# ============================================================
# STRUCTURED LLM OUTPUT
# ============================================================


class AnswerClaim(BaseModel):
    """
    One material claim made by the RAG system.
    """

    claim: str

    supporting_chunk_ids: list[str] = Field(
        default_factory=list
    )


class GroundedLLMResponse(BaseModel):
    """
    Structured response produced by the LLM.

    The model references evidence only through chunk IDs.
    Citation metadata is NOT generated by the model.
    """

    answer: str

    claims: list[AnswerClaim]

    limitations: list[str] = Field(
        default_factory=list
    )


# ============================================================
# TRUSTED CITATION
# ============================================================


class Citation(BaseModel):
    """
    Citation constructed deterministically from trusted
    retrieved-document metadata.
    """

    chunk_id: str
    document_id: str
    document_name: str
    document_type: str | None
    page_number: int | None


class GroundedClaim(BaseModel):
    """
    Validated claim plus trusted citations.
    """

    claim: str

    citations: list[Citation]


class GroundedAnswerResult(BaseModel):
    """
    Final application-level RAG response.
    """

    answer: str

    claims: list[GroundedClaim]

    citations: list[Citation]

    limitations: list[str]


# ============================================================
# GROUNDED ANSWER GENERATOR
# ============================================================


class GroundedAnswerGenerator:
    """
    Generates an answer using only retrieved evidence.

    Important design:

        LLM:
            creates answer
            creates claims
            references chunk IDs

        Python:
            validates chunk IDs
            creates citation metadata
            rejects unsupported claims
    """

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
    ) -> None:

        self.model = model
        self.client = OpenAI()

    # ========================================================
    # PUBLIC API
    # ========================================================

    def generate(
        self,
        query: str,
        documents: list[Document],
    ) -> GroundedAnswerResult:

        query = query.strip()

        if not query:
            raise ValueError(
                "Query cannot be empty."
            )

        if not documents:
            raise ValueError(
                "At least one evidence document is required."
            )

        context = self._build_context(
            documents
        )

        response = self.client.responses.parse(
            model=self.model,
            instructions=(
                "You are an evidence-grounded credit analysis "
                "assistant for a commercial bank. "
                "Answer the user's question using ONLY the "
                "evidence chunks supplied in the context. "
                "Do not use outside knowledge. "
                "Do not invent facts, numbers, documents, "
                "page numbers, or chunk IDs. "
                "For every material claim, provide one or more "
                "supporting_chunk_ids from the supplied context. "
                "If the available evidence is insufficient to "
                "support a conclusion, explicitly state that "
                "limitation rather than guessing. "
                "Do not make a final credit approval or rejection "
                "decision."
            ),
            input=(
                f"QUESTION:\n"
                f"{query}\n\n"
                f"EVIDENCE:\n"
                f"{context}"
            ),
            text_format=GroundedLLMResponse,
        )

        parsed = response.output_parsed

        if parsed is None:
            raise RuntimeError(
                "Grounded answer model returned no "
                "structured result."
            )

        return self._validate_and_build_result(
            llm_response=parsed,
            documents=documents,
        )

    # ========================================================
    # CONTEXT
    # ========================================================

    @staticmethod
    def _build_context(
        documents: list[Document],
    ) -> str:

        sections = []

        for document in documents:

            metadata = document.metadata

            sections.append(
                "\n".join(
                    [
                        (
                            f"CHUNK_ID: "
                            f"{metadata['chunk_id']}"
                        ),
                        (
                            f"DOCUMENT: "
                            f"{metadata['document_name']}"
                        ),
                        (
                            f"DOCUMENT_TYPE: "
                            f"{metadata['document_type']}"
                        ),
                        (
                            f"PAGE: "
                            f"{metadata['page_number']}"
                        ),
                        "TEXT:",
                        document.page_content,
                    ]
                )
            )

        return "\n\n---\n\n".join(
            sections
        )

    # ========================================================
    # VALIDATION + CITATION CONSTRUCTION
    # ========================================================

    @staticmethod
    def _validate_and_build_result(
        llm_response: GroundedLLMResponse,
        documents: list[Document],
    ) -> GroundedAnswerResult:

        # ----------------------------------------------------
        # Build trusted lookup from retrieved context.
        # ----------------------------------------------------

        document_lookup = {
            document.metadata["chunk_id"]: document
            for document in documents
        }

        grounded_claims: list[GroundedClaim] = []

        citation_lookup: dict[
            str,
            Citation,
        ] = {}

        # ----------------------------------------------------
        # Validate every material claim.
        # ----------------------------------------------------

        for claim in llm_response.claims:

            if not claim.supporting_chunk_ids:
                raise RuntimeError(
                    "Unsupported claim returned by LLM: "
                    f"{claim.claim}"
                )

            claim_citations = []

            for chunk_id in claim.supporting_chunk_ids:

                document = document_lookup.get(
                    chunk_id
                )

                if document is None:
                    raise RuntimeError(
                        "LLM referenced an unknown chunk_id: "
                        f"{chunk_id}"
                    )

                metadata = document.metadata

                citation = Citation(
                    chunk_id=metadata["chunk_id"],
                    document_id=metadata["document_id"],
                    document_name=metadata["document_name"],
                    document_type=metadata[
                        "document_type"
                    ],
                    page_number=metadata[
                        "page_number"
                    ],
                )

                claim_citations.append(
                    citation
                )

                citation_lookup[
                    citation.chunk_id
                ] = citation

            grounded_claims.append(
                GroundedClaim(
                    claim=claim.claim,
                    citations=claim_citations,
                )
            )

        return GroundedAnswerResult(
            answer=llm_response.answer,
            claims=grounded_claims,
            citations=list(
                citation_lookup.values()
            ),
            limitations=llm_response.limitations,
        )