from __future__ import annotations

from typing import Any

from langchain_core.documents import Document
from langchain_core.retrievers import BaseRetriever
from pydantic import Field

from src.rag.query_embedding import QueryEmbedder
from src.rag.vector_search import search_similar_chunks


class CreditDocumentRetriever(BaseRetriever):
    """
    LangChain retriever for the AI Credit Intelligence Platform.

    This retriever intentionally reuses our existing retrieval
    implementation rather than creating another vector store.

    Retrieval flow:

        User query
            ↓
        QueryEmbedder
            ↓
        OpenAI query embedding
            ↓
        PostgreSQL / pgvector
            ↓
        Customer/application filtering
            ↓
        Optional document-type filtering
            ↓
        Cosine similarity ranking
            ↓
        LangChain Document objects

    The retriever preserves provenance metadata required later
    for grounded answers and citations.
    """

    # =========================================================
    # TRUSTED CASE SCOPE
    # =========================================================

    customer_id: str = Field(
        ...,
        description=(
            "Trusted customer identifier used to scope retrieval."
        ),
    )

    application_id: str = Field(
        ...,
        description=(
            "Trusted loan application identifier used "
            "to scope retrieval."
        ),
    )

    # =========================================================
    # RETRIEVAL CONFIGURATION
    # =========================================================

    top_k: int = Field(
        default=5,
        ge=1,
        description=(
            "Maximum number of semantically similar chunks "
            "to retrieve."
        ),
    )

    document_type: str | None = Field(
        default=None,
        description=(
            "Optional document-type metadata filter. "
            "If None, all document types within the case "
            "are eligible for semantic retrieval."
        ),
    )

    # =========================================================
    # LANGCHAIN RETRIEVER IMPLEMENTATION
    # =========================================================

    def _get_relevant_documents(
        self,
        query: str,
        *,
        run_manager: Any = None,
    ) -> list[Document]:
        """
        Retrieve relevant document chunks for a natural-language
        query and convert them into LangChain Document objects.
        """

        query = query.strip()

        if not query:
            raise ValueError(
                "Query cannot be empty."
            )

        # -----------------------------------------------------
        # Step 1:
        # Convert the user's natural-language query into the
        # same embedding space used by document chunks.
        # -----------------------------------------------------

        embedder = QueryEmbedder()

        query_embedding = embedder.embed(
            query
        )

        # -----------------------------------------------------
        # Step 2:
        # Perform case-scoped pgvector semantic search.
        #
        # document_type is optional.
        #
        # Example:
        #
        # document_type="FINANCIAL_STATEMENT"
        #
        # restricts retrieval to financial statements.
        # -----------------------------------------------------

        results = search_similar_chunks(
            query_embedding=query_embedding,
            customer_id=self.customer_id,
            application_id=self.application_id,
            top_k=self.top_k,
            document_type=self.document_type,
        )

        # -----------------------------------------------------
        # Step 3:
        # Convert our internal SearchResult objects into the
        # standard LangChain Document representation.
        # -----------------------------------------------------

        documents: list[Document] = []

        for result in results:

            # Start with metadata generated by our own
            # retrieval/provenance layer.
            metadata = {
                "chunk_id": result.chunk_id,
                "document_id": result.document_id,
                "document_name": result.document_name,
                "document_type": result.document_type,
                "chunk_type": result.chunk_type,
                "page_number": result.page_number,
                "cosine_distance": result.cosine_distance,
                "similarity_score": result.similarity_score,
            }

            # -------------------------------------------------
            # Preserve additional metadata from document_chunks.
            #
            # We add stored metadata first, then reapply trusted
            # provenance fields so arbitrary stored metadata
            # cannot overwrite chunk_id/document_id/etc.
            # -------------------------------------------------

            combined_metadata = {
                **result.metadata,
                **metadata,
            }

            document = Document(
                page_content=result.chunk_text,
                metadata=combined_metadata,
            )

            documents.append(
                document
            )

        return documents